run:
  deadline: 10m

issues:
  exclude-dirs:
    # foreign languages give false positives for misspell
    - ui/values/localizable

output:
  formats: github-actions,colored-line-number

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gosimple
    - unconvert
    - ineffassign
    - revive
    - goimports
    - unparam
    - errcheck

linters-settings:
  errcheck:
    # Individual function to be ignored one per line.
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*github.com/jrick/logrotate/rotator.Rotator).Write
