name: Cross-Platform Build on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: 386
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.os }}/${{ matrix.arch }}
        push: false
        tags: user/app:latest
        build-args: |
          BUILDOS=${{ matrix.os }}
          BUILDARCH=${{ matrix.arch }}
          BUILDNAME=myapp-${{ matrix.os }}-${{ matrix.arch }}
